version: "3.8"
services:

  db:
    image: postgres
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - postgres.env
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "db", "-p", "5432"]
      timeout: 10s
      retries: 3
      interval: 5s
      start_period: 5s
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/home/aplicacao
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db